### ISSUE TITLE
Investigate  and update the method of journal search using iSSN

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/nihms-submission-etl#34]
ISSN used to have the format of `nnnn-nnnn` - it's been updated to have the format of `pubtype:nnnn-nnnn`

Any code within this module that perform a journal search needs to be updated to account for this change.

**Comment by emetsger** [comment]
NIHMS ETL uses of the `PassClient`:
creates
- publication
- submission
- repository copy

updates
- publication
- submission
- repository copy
- deposit

reads
- deposit
- grant
- publication
- submission
- repository copy

finds
- grants
- repository copy
- publication
- journal
- deposit

Notably NIHMS ETL does not create or update `Journal` records, it only searches for them.  So any remediation with respect to the `pub-type:issn` format of `Journal.issns` can be scoped to updating the search logic (don't have to worry about creation of `Journal`, just searching).

**Comment by emetsger** [comment]
After investigation we show that in the `pass-docker` environment:
* of the `21154` `Publication` resources indexed in `pass-docker`, none of them have a linked `Journal` (i.e. `Publication.journal` is null for each record)
* of the `30510` indexed `Journal` resources, none of them have a `Journal.publisher`

What _is_ required is that a journal (lower-case "j") can be resolved from information in a `Publication`.  As long as a `Publication` carries a DOI or a PubMed ID, external services can be used to resolve journal information.  It is therefore not necessary or required for a `Publication` to link to a `Journal`.

As a result, the code that attempts an ISSN lookup to link a `Publication` to a `Journal` will be removed, and code that insures a DOI or PMID is present on `Publication` will be added.
